title MuliRecovery
linux /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd /%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% quiet loglevel=0 systemd.show_status=false rd.systemd.show_status=false systemd.status_unit_format=description rd.driver.blacklist=floppy modprobe.blacklist=floppy
